# Generated by Django 5.2.6 on 2025-09-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='reviews_count',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
